set(CMAKE_C_COMPILER "${PREFIX}/bin/i686-pc-mingw32-gcc" CACHE STRING "" FORCE)
set(CMAKE_CXX_COMPILER "${PREFIX}/i686-pc-mingw32-g++" CACHE STRING "" FORCE)
# message(STATUS "${CMAKE_C_STANDARD_INCLUDE_DIRECTORIES}")
