cmake_minimum_required(VERSION 3.5.1)

set(CMAKE_TOOLCHAIN_FILE "helpers/gcc-guest.cmake" CACHE BOOL "" FORCE)
include(${CMAKE_TOOLCHAIN_FILE})

set(COLINUX_HOST_OS "winnt" CACHE BOOL "" FORCE)
set(USER_TOPDIR "${CMAKE_CURRENT_LIST_DIR}" CACHE BOOL "" FORCE)
set(DOWNLOADS "${USER_TOPDIR}/download" CACHE BOOL "" FORCE)
set(BUILD_DIR "${USER_TOPDIR}/build" CACHE BOOL "" FORCE)
set(PREFIX "${USER_TOPDIR}/mingw32" CACHE BOOL "" FORCE)
# set(KERNEL_VERSION "2.6.33")
# set(COLINUX_TARGET_KERNEL_PATH "${BUILD_DIR}/linux-${KERNEL_VERSION}")
set(COLINUX_TARGET_KERNEL_SOURCE "${BUILD_DIR}/linux-${KERNEL_VERSION}-source" CACHE BOOL "" FORCE)
set(COLINUX_TARGET_KERNEL_BUILD "${BUILD_DIR}/linux-${KERNEL_VERSION}-build" CACHE BOOL "" FORCE)
set(COLINUX_TARGET_MODULE_PATH "${COLINUX_TARGET_KERNEL_BUILD}/_install" CACHE BOOL "" FORCE)
# set(COLINUX_HOST_KERNEL_DIR /lib/modules/`uname -r`/build CACHE BOOL "" FORCE)
set(COLINUX_INSTALL_DIR "${USER_TOPDIR}/dist" CACHE BOOL "" FORCE)

string(
    RANDOM
    ALPHABET 0123456789
    LENGTH 4
    RAND_ID
)
set(COLINUX_BUILD_LOG "${USER_TOPDIR}/log/build-colinux-${RAND_ID}.log" CACHE BOOL "" FORCE)
set(COLINUX_BUILD_ERR "${USER_TOPDIR}/log/build-colinux-${RAND_ID}.err" CACHE BOOL "" FORCE)

set(COLINUX_KERNEL_UNTAR FALSE CACHE BOOL "" FORCE)
set(COLINUX_KERNEL_STRIP FALSE CACHE BOOL "" FORCE)
# set(COLINUX_DEPMOD /sbin/depmod CACHE BOOL "" FORCE)

set(COLINUX_GCC_GUEST_TARGET "i686-co-linux" CACHE BOOL "" FORCE)
set(COLINUX_GCC_GUEST_PATH "${PREFIX}/${COLINUX_GCC_GUEST_TARGET}/bin")
